//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZarDevs.DependencyInjection.ZarIoc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZarDevs.DependencyInjection.ZarIoc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        internal static string CategoryException {
            get {
                return ResourceManager.GetString("CategoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading XML.
        /// </summary>
        internal static string CategoryLoading {
            get {
                return ResourceManager.GetString("CategoryLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing XML.
        /// </summary>
        internal static string CategoryParsing {
            get {
                return ResourceManager.GetString("CategoryParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IOC Generation Error.
        /// </summary>
        internal static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IOC Generation Exception: {0}.
        /// </summary>
        internal static string TitleException {
            get {
                return ResourceManager.GetString("TitleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IOC Generation Information.
        /// </summary>
        internal static string TitleInformation {
            get {
                return ResourceManager.GetString("TitleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IOC Generation Exception &apos;{0}&apos;.
        /// </summary>
        internal static string ZarE001 {
            get {
                return ResourceManager.GetString("ZarE001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; is null or empty.
        /// </summary>
        internal static string ZarE002 {
            get {
                return ResourceManager.GetString("ZarE002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly at index {0} is null or empty.
        /// </summary>
        internal static string ZarE003 {
            get {
                return ResourceManager.GetString("ZarE003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; is not referenced.
        /// </summary>
        internal static string ZarE004 {
            get {
                return ResourceManager.GetString("ZarE004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a total of {0} binding files..
        /// </summary>
        internal static string ZarI001 {
            get {
                return ResourceManager.GetString("ZarI001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file &apos;{0}&apos;.
        /// </summary>
        internal static string ZarI002 {
            get {
                return ResourceManager.GetString("ZarI002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading binding &apos;{0}&apos;.
        /// </summary>
        internal static string ZarI003 {
            get {
                return ResourceManager.GetString("ZarI003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Scanned Assembly &apos;{0}&apos;.
        /// </summary>
        internal static string ZarI004 {
            get {
                return ResourceManager.GetString("ZarI004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added assembly &apos;{0}&apos; and IDependencyRegistration class &apos;{1}&apos;.
        /// </summary>
        internal static string ZarI005 {
            get {
                return ResourceManager.GetString("ZarI005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added assembly &apos;{0}&apos; and class &apos;{1}&apos; with method &apos;{2}&apos;.
        /// </summary>
        internal static string ZarI006 {
            get {
                return ResourceManager.GetString("ZarI006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed assembly &apos;{0}&apos; and IDependencyRegistration class &apos;{1}&apos; in favour of assembly scan due to merge.
        /// </summary>
        internal static string ZarI007 {
            get {
                return ResourceManager.GetString("ZarI007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating instances for assembly &apos;{0}&apos;.
        /// </summary>
        internal static string ZarI008 {
            get {
                return ResourceManager.GetString("ZarI008", resourceCulture);
            }
        }
    }
}
